apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ontap-thin
